/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import util.HibernateUtil;

/**
 *
 * @author ROZER
 */
public class ConsultasView extends javax.swing.JFrame {

    private final ConsultasController consultas;
    /**
     * Creates new form ConsultasView
     */
    public ConsultasView() {
	initComponents();
	this.setLocationRelativeTo(this);
	this.setTitle("Consultora IT");
	
	consultas = new ConsultasController(this);
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgConsultas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_consulta1 = new javax.swing.JButton();
        btn_consulta2 = new javax.swing.JButton();
        btn_consulta3 = new javax.swing.JButton();
        btn_consulta4 = new javax.swing.JButton();
        btn_consulta5 = new javax.swing.JButton();
        btn_consulta6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabConsultas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 450));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(750, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 450));

        btn_consulta1.setBackground(new java.awt.Color(0, 204, 51));
        btn_consulta1.setText("Consulta 1");
        btn_consulta1.setToolTipText("Consulta por apellido, salario y número de empeado con salario inferior a 1600");
        bgConsultas.add(btn_consulta1);

        btn_consulta2.setBackground(new java.awt.Color(0, 204, 51));
        btn_consulta2.setText("Consulta 2");
        btn_consulta2.setToolTipText("Consulta por número de empleado, departamento y salario de los empleados, ordenados de menor a mayor salario.");
        bgConsultas.add(btn_consulta2);

        btn_consulta3.setBackground(new java.awt.Color(0, 204, 51));
        btn_consulta3.setText("Consulta 3");
        btn_consulta3.setToolTipText("Consulta por datos de empleados cuyo departamento no esté en GRANADA");
        bgConsultas.add(btn_consulta3);

        btn_consulta4.setBackground(new java.awt.Color(0, 204, 51));
        btn_consulta4.setText("Consulta 4");
        btn_consulta4.setToolTipText("Consulta por Apellido, salario y número de departamento de los empleados cuyo salario sea mayor que el máximo salario del departamento 10.");
        bgConsultas.add(btn_consulta4);

        btn_consulta5.setBackground(new java.awt.Color(0, 204, 51));
        btn_consulta5.setText("Consulta 5");
        btn_consulta5.setToolTipText("Consulta por Empleados con salario menor que alguno de los empleados del departamento 20.");
        bgConsultas.add(btn_consulta5);

        btn_consulta6.setBackground(new java.awt.Color(0, 204, 51));
        btn_consulta6.setText("Consulta 6");
        btn_consulta6.setToolTipText("Consulta por Mostrar nombre y total de empleados de aquellos departamentos con más de un empleado adscrito. Ordena el resultado por número de empleado.");
        bgConsultas.add(btn_consulta6);

        tabConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabConsultas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_consulta1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_consulta2)
                        .addGap(18, 18, 18)
                        .addComponent(btn_consulta3)
                        .addGap(18, 18, 18)
                        .addComponent(btn_consulta4)
                        .addGap(18, 18, 18)
                        .addComponent(btn_consulta5)
                        .addGap(18, 18, 18)
                        .addComponent(btn_consulta6)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_consulta1)
                    .addComponent(btn_consulta2)
                    .addComponent(btn_consulta3)
                    .addComponent(btn_consulta4)
                    .addComponent(btn_consulta5)
                    .addComponent(btn_consulta6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(ConsultasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(ConsultasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(ConsultasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(ConsultasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new ConsultasView().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup bgConsultas;
    public javax.swing.JButton btn_consulta1;
    public javax.swing.JButton btn_consulta2;
    public javax.swing.JButton btn_consulta3;
    public javax.swing.JButton btn_consulta4;
    public javax.swing.JButton btn_consulta5;
    public javax.swing.JButton btn_consulta6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabConsultas;
    // End of variables declaration//GEN-END:variables
}
